language: cpp

# use docker in travis
sudo: false

# reduce clone time by only getting the latest commit and not the whole history (default for travis is 100)
git:
  depth: 1

# send notifications to stack as well as email
# build on both Linux and OSX (finally)
os:
  - linux
# build with both gcc and clang to ensure compatibility
compiler:
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang

before_install:
  - bash .travis.sh
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CC" = "gcc" ] ; then export CC=gcc-4.8 CXX=g++-4.8 ; fi

script:
  - test -d _build || mkdir _build
  - test -d _install || mkdir _install
  - cd _build
  - cmake -DCMAKE_INSTALL_PREFIX=../_install ..
  - make -j4
  - echo "done"
  - ls -a
 
deploy:
  provider: releases
  user: Xeddius
  file:
  password:
    secure: "VGDYUwK2ka4PXaAVVLoRbb8dYKarJcpkF3NG/nZwXS2RkbDoXsLr9btNRmejUc09+Y4YsgO8ZaeHh6py3S2YyJUWaZBFpr2I/Ue+mEo63ir396JACUk5sDxHyI47VvEMZYI5swrnPXdPXCWKG4Bl3FJdZnmA9e+SjMoTvu+2q66FbF+DP4zyrBV6Aq/m3fP2gj/9wiD2DkrPag/I4Gb/tI0yEiDaJKNOovDT4bec0DC1jWqxhXWa2EhMId6ocebZS/KYNbGk8Ls8R7K+Ni+cy9cVNte7wwps1f1Oh3948kvkNDce8LTeYznWLqL62LsfryckrqPpW6dhV6zo7g1csKKPh5gdX5j9MKVOzmVYJO4S9yitjzOk1HaiVbtTkXUUIsdNu1+IZK3SsdM0+rF6kgC366rBCsBZkr5VHbwuMrKvkx9hJBUyiyHuNzgW5B9gkSrcF2wd737IC9e0sxfj570AUjrByZvp/ZIOXAqsbTe51Geov4odO27y+XBnR+fU3/EOxzxDFOmez0byOZlUjoq2I609YazuGo7a6e7b/WqDTpZvRYLsbeL2u0knVYyKg0u5DKoK+jH/a5Yg1pG+zSR186PTarq00RP3uraXiFC3FOTsCoXxScx2O9TDi+UnUsjukmiPhpIeLvgr17HV2EG76JgJMfRJxBJfBoeB/So="
  skip_cleanup: true
  on:
    tags: true
